# SPDX-License-Identifier: MIT
name: lint

permissions: {}

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]
  push:
  workflow_dispatch:

jobs:
  super-linter:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for super-linter
      - name: Super-Linter
        run: ./build/tools/super-linter.sh || true # temporary suppress error
